name: Examples
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Install Z3 (required for Day 24)
        uses: pavpanchekha/setup-z3@1.2.2
        with:
          version: 4.8.13
      - name: Run examples
        timeout-minutes: 25
        run: |
          for file in $(ls day*.rb)
          do
            echo $file
            bundle exec ruby $file --debug || exit 1
          done
          exit 0
